# Site settings
title: Johan Bjäreholt
description: >
  My name is Johan Bjäreholt, and I am a software engineering student from Sweden.
  I am a curious guy who looks for people to share interests and ideas with.
  This sites purpose is to showcase my free time projects and inspire others.

url: "johan-bjareholt.github.io" # the base hostname & protocol for your site

permalink: /post/:title/
timezone: Europe/Stockholm

# Contact info
name: Johan Bjäreholt
email: johan@bjareho.lt
github_username:  johan-bjareholt
linkedin_username: 234482057
soundcloud_username: johanbjare

# Build settings
markdown: kramdown
